# Generated by Django 5.2.8 on 2025-11-07 18:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('name', models.CharField(help_text="e.g., '2025 Formula 1 Season'", max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['year'], name='analytics_s_year_b68a91_idx'), models.Index(fields=['is_active'], name='analytics_s_is_acti_446203_idx')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='analytics.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CurrentLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_space', models.DecimalField(decimal_places=2, help_text='Remaining cap space in millions (M)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver1', to='analytics.driver')),
                ('driver2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver2', to='analytics.driver')),
                ('driver3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver3', to='analytics.driver')),
                ('driver4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver4', to='analytics.driver')),
                ('driver5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver5', to='analytics.driver')),
                ('drs_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drs_driver', to='analytics.driver')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='analytics.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='analytics.team')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('fantasy_price', models.DecimalField(decimal_places=2, help_text='Fantasy price in millions', max_digits=10)),
                ('price_change', models.DecimalField(decimal_places=2, help_text='Price change, negative for decreases', max_digits=10)),
                ('season_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('percent_picked', models.DecimalField(decimal_places=2, help_text='Percentage of teams that have picked this constructor', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_snapshots', to='analytics.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analytics.team')),
            ],
            options={
                'ordering': ['-snapshot_date', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='DriverSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('fantasy_price', models.DecimalField(decimal_places=2, help_text='Fantasy price in millions (e.g., 30.4 for $30.4M)', max_digits=10)),
                ('price_change', models.DecimalField(decimal_places=2, help_text='Price change, negative for decreases', max_digits=10)),
                ('season_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('percent_picked', models.DecimalField(decimal_places=2, help_text='Percentage of teams that have picked this driver', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analytics.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_snapshots', to='analytics.season')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_snapshots', to='analytics.team')),
            ],
            options={
                'ordering': ['-snapshot_date', 'driver__last_name'],
                'indexes': [models.Index(fields=['snapshot_date'], name='analytics_d_snapsho_3cb244_idx'), models.Index(fields=['driver', 'snapshot_date'], name='analytics_d_driver__67fd36_idx'), models.Index(fields=['season', 'snapshot_date'], name='analytics_d_season__08b320_idx'), models.Index(fields=['-fantasy_price'], name='analytics_d_fantasy_31998d_idx'), models.Index(fields=['-season_points'], name='analytics_d_season__fe0b15_idx')],
                'unique_together': {('driver', 'snapshot_date')},
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['last_name', 'first_name'], name='analytics_d_last_na_a3d000_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorsnapshot',
            index=models.Index(fields=['snapshot_date'], name='analytics_c_snapsho_de015f_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorsnapshot',
            index=models.Index(fields=['team', 'snapshot_date'], name='analytics_c_team_id_b67037_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorsnapshot',
            index=models.Index(fields=['season', 'snapshot_date'], name='analytics_c_season__50eb51_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorsnapshot',
            index=models.Index(fields=['-fantasy_price'], name='analytics_c_fantasy_208e48_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorsnapshot',
            index=models.Index(fields=['-season_points'], name='analytics_c_season__3d3c31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='constructorsnapshot',
            unique_together={('team', 'snapshot_date')},
        ),
    ]
