# Generated by Django 5.2.8 on 2025-11-07 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('name', models.CharField(help_text="e.g., '2025 Formula 1 Season'", max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['year'], name='analytics_s_year_b68a91_idx'), models.Index(fields=['is_active'], name='analytics_s_is_acti_446203_idx')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='analytics.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ConstructorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('fantasy_price', models.DecimalField(decimal_places=2, help_text='Fantasy price in millions', max_digits=10)),
                ('price_change', models.DecimalField(decimal_places=2, help_text='Price change, negative for decreases', max_digits=10)),
                ('season_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('percent_picked', models.DecimalField(decimal_places=2, help_text='Percentage of teams that have picked this constructor', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_snapshots', to='analytics.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analytics.team')),
            ],
            options={
                'ordering': ['-snapshot_date', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='DriverSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('fantasy_price', models.DecimalField(decimal_places=2, help_text='Fantasy price in millions (e.g., 30.4 for $30.4M)', max_digits=10)),
                ('price_change', models.DecimalField(decimal_places=2, help_text='Price change, negative for decreases', max_digits=10)),
                ('season_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('percent_picked', models.DecimalField(decimal_places=2, help_text='Percentage of teams that have picked this driver', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analytics.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_snapshots', to='analytics.season')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_snapshots', to='analytics.team')),
            ],
            options={
                'ordering': ['-snapshot_date', 'driver__last_name'],
                'indexes': [models.Index(fields=['snapshot_date'], name='analytics_d_snapsho_3cb244_idx'), models.Index(fields=['driver', 'snapshot_date'], name='analytics_d_driver__67fd36_idx'), models.Index(fields=['season', 'snapshot_date'], name='analytics_d_season__08b320_idx'), models.Index(fields=['-fantasy_price'], name='analytics_d_fantasy_31998d_idx'), models.Index(fields=['-season_points'], name='analytics_d_season__fe0b15_idx')],
                'unique_together': {('driver', 'snapshot_date')},
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['last_name', 'first_name'], name='analytics_d_last_na_a3d000_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorsnapshot',
            index=models.Index(fields=['snapshot_date'], name='analytics_c_snapsho_de015f_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorsnapshot',
            index=models.Index(fields=['team', 'snapshot_date'], name='analytics_c_team_id_b67037_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorsnapshot',
            index=models.Index(fields=['season', 'snapshot_date'], name='analytics_c_season__50eb51_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorsnapshot',
            index=models.Index(fields=['-fantasy_price'], name='analytics_c_fantasy_208e48_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorsnapshot',
            index=models.Index(fields=['-season_points'], name='analytics_c_season__3d3c31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='constructorsnapshot',
            unique_together={('team', 'snapshot_date')},
        ),
    ]
