# Generated by Django 5.2.8 on 2025-11-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentlineup',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Current Lineup', 'verbose_name_plural': 'Current Lineups'},
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Bahrain', 'Australia', 'Monaco'", max_length=100)),
                ('round_number', models.IntegerField(help_text='Race number in season (1 for first race, 2 for second, etc.)')),
                ('race_date', models.DateField(blank=True, null=True)),
                ('circuit_name', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='analytics.season')),
            ],
            options={
                'ordering': ['season', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='DriverRacePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(help_text='Total fantasy points earned in this race weekend')),
                ('fantasy_price', models.DecimalField(decimal_places=2, help_text="Driver's fantasy price at time of race (for value calculations)", max_digits=10)),
                ('season_points_cumulative', models.IntegerField(help_text='Cumulative season points after this race')),
                ('had_qualifying', models.BooleanField(default=False)),
                ('had_sprint', models.BooleanField(default=False)),
                ('had_race', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_performances', to='analytics.driver')),
                ('team', models.ForeignKey(help_text='Team at time of race (handles mid-season transfers)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.team')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_performances', to='analytics.race')),
            ],
            options={
                'verbose_name': 'Driver Race Performance',
                'verbose_name_plural': 'Driver Race Performances',
                'ordering': ['race__season', 'race__round_number', 'driver'],
            },
        ),
        migrations.CreateModel(
            name='DriverEventScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('qualifying', 'Qualifying'), ('sprint', 'Sprint Race'), ('race', 'Main Race'), ('weekend', 'Weekend Bonus')], db_index=True, help_text='Type of event (qualifying, sprint, race, weekend)', max_length=20)),
                ('scoring_item', models.CharField(help_text="Specific scoring action (e.g., 'Qualifying Position', 'Race Overtake Bonus')", max_length=100)),
                ('points', models.IntegerField(help_text='Points earned for this item (can be negative)')),
                ('position', models.IntegerField(blank=True, help_text='Final position if applicable (1st, 2nd, etc.)', null=True)),
                ('frequency', models.IntegerField(blank=True, help_text='Count for frequency-based items (overtakes, positions gained)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_scores', to='analytics.driverraceperformance')),
            ],
            options={
                'verbose_name': 'Driver Event Score',
                'verbose_name_plural': 'Driver Event Scores',
                'ordering': ['performance__race', 'event_type', 'scoring_item'],
                'indexes': [models.Index(fields=['performance', 'event_type'], name='analytics_d_perform_561fbf_idx'), models.Index(fields=['event_type', 'scoring_item'], name='analytics_d_event_t_6bf880_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['season', 'round_number'], name='analytics_r_season__7e9ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['name'], name='analytics_r_name_bd2d07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('season', 'name'), ('season', 'round_number')},
        ),
        migrations.AddIndex(
            model_name='driverraceperformance',
            index=models.Index(fields=['driver', 'race'], name='analytics_d_driver__8f8908_idx'),
        ),
        migrations.AddIndex(
            model_name='driverraceperformance',
            index=models.Index(fields=['race', '-total_points'], name='analytics_d_race_id_1a27d8_idx'),
        ),
        migrations.AddIndex(
            model_name='driverraceperformance',
            index=models.Index(fields=['team', 'race'], name='analytics_d_team_id_b19a46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverraceperformance',
            unique_together={('driver', 'race')},
        ),
    ]
