# Generated by Django 5.2.8 on 2025-11-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_driver_race_outcomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorRacePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(help_text='Total fantasy points earned in this race weekend')),
                ('fantasy_price', models.DecimalField(decimal_places=2, help_text="Constructor's fantasy price at time of race", max_digits=10)),
                ('season_points_cumulative', models.IntegerField(help_text='Cumulative season points after this race')),
                ('had_qualifying', models.BooleanField(default=False)),
                ('had_sprint', models.BooleanField(default=False)),
                ('had_race', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_performances', to='analytics.race')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_performances', to='analytics.team')),
            ],
            options={
                'verbose_name': 'Constructor Race Performance',
                'verbose_name_plural': 'Constructor Race Performances',
                'ordering': ['race__season', 'race__round_number', 'team'],
            },
        ),
        migrations.CreateModel(
            name='ConstructorEventScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('qualifying', 'Qualifying'), ('sprint', 'Sprint Race'), ('race', 'Main Race'), ('weekend', 'Weekend Bonus')], db_index=True, help_text='Type of event (qualifying, sprint, race, weekend)', max_length=20)),
                ('scoring_item', models.CharField(help_text="Specific scoring action (e.g., 'Qualifying Position', 'Pitstop Bonus')", max_length=100)),
                ('points', models.IntegerField(help_text='Points earned for this item (can be negative)')),
                ('position', models.IntegerField(blank=True, help_text='Final position if applicable', null=True)),
                ('frequency', models.IntegerField(blank=True, help_text='Count for frequency-based items (pitstops, positions gained)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_scores', to='analytics.constructorraceperformance')),
            ],
            options={
                'verbose_name': 'Constructor Event Score',
                'verbose_name_plural': 'Constructor Event Scores',
                'ordering': ['performance__race', 'event_type', 'scoring_item'],
            },
        ),
        migrations.AddIndex(
            model_name='constructorraceperformance',
            index=models.Index(fields=['team', 'race'], name='analytics_c_team_id_7369ed_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorraceperformance',
            index=models.Index(fields=['race', '-total_points'], name='analytics_c_race_id_3c5d36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='constructorraceperformance',
            unique_together={('team', 'race')},
        ),
        migrations.AddIndex(
            model_name='constructoreventscore',
            index=models.Index(fields=['performance', 'event_type'], name='analytics_c_perform_6d6c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='constructoreventscore',
            index=models.Index(fields=['event_type', 'scoring_item'], name='analytics_c_event_t_8518b5_idx'),
        ),
    ]
