# Generated by Django 5.2.8 on 2025-11-10 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_constructors_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Circuit name (e.g., 'Silverstone Circuit', 'Circuit de Monaco')", max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Circuit',
                'verbose_name_plural': 'Circuits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('Practice 1', 'Free Practice 1'), ('Practice 2', 'Free Practice 2'), ('Practice 3', 'Free Practice 3'), ('Qualifying', 'Qualifying'), ('Sprint Qualifying', 'Sprint Qualifying'), ('Sprint', 'Sprint Race'), ('Race', 'Race')], help_text='Type of session (Practice 1, Qualifying, Race, etc.)', max_length=30)),
                ('session_number', models.IntegerField(help_text='Session number in weekend (1-5, matching FastF1 Session1-Session5)')),
                ('session_date_local', models.CharField(blank=True, help_text='Session date/time in local timezone (as string from FastF1)', max_length=100)),
                ('session_date_utc', models.DateTimeField(blank=True, help_text='Session date/time in UTC', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['race', 'session_number'],
            },
        ),
        migrations.RemoveField(
            model_name='race',
            name='circuit_name',
        ),
        migrations.AddField(
            model_name='race',
            name='event_date',
            field=models.DateField(blank=True, help_text='Official event date from FastF1 (usually race day)', null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='event_format',
            field=models.CharField(choices=[('conventional', 'Conventional Weekend'), ('sprint', 'Sprint Weekend'), ('testing', 'Testing')], default='conventional', help_text='Weekend format (conventional, sprint, testing)', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='f1_api_support',
            field=models.BooleanField(default=True, help_text='Whether FastF1 API has data for this event'),
        ),
        migrations.AddField(
            model_name='race',
            name='location',
            field=models.CharField(blank=True, help_text="City/location name (e.g., 'Melbourne', 'Silverstone')", max_length=100),
        ),
        migrations.AddField(
            model_name='race',
            name='official_event_name',
            field=models.CharField(blank=True, help_text='Full official event name from FIA', max_length=255),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateField(blank=True, help_text='Main race date', null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='circuit',
            field=models.ForeignKey(blank=True, help_text='The circuit where this race takes place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='analytics.circuit'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['event_format'], name='analytics_r_event_f_222591_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['circuit'], name='analytics_r_circuit_2c2c3c_idx'),
        ),
        migrations.AddField(
            model_name='session',
            name='race',
            field=models.ForeignKey(help_text='The race weekend this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.race'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['race', 'session_number'], name='analytics_s_race_id_613ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_type'], name='analytics_s_session_07eb38_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_date_utc'], name='analytics_s_session_c779a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('race', 'session_number')},
        ),
    ]
