# Generated by Django 5.2.8 on 2025-11-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='rotation',
            field=models.FloatField(blank=True, help_text='Track rotation/orientation in degrees (for track map visualization)', null=True),
        ),
        migrations.CreateModel(
            name='Corner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Corner number (1, 2, 3, etc.)')),
                ('letter', models.CharField(blank=True, help_text="Corner letter designation (e.g., 'A', 'B' for chicanes)", max_length=10)),
                ('x', models.FloatField(help_text='X coordinate in circuit coordinate system')),
                ('y', models.FloatField(help_text='Y coordinate in circuit coordinate system')),
                ('angle', models.FloatField(help_text='Corner angle in degrees')),
                ('distance', models.FloatField(help_text='Distance from start line in meters')),
                ('circuit', models.ForeignKey(help_text='The circuit this corner belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='corners', to='analytics.circuit')),
            ],
            options={
                'verbose_name': 'Corner',
                'verbose_name_plural': 'Corners',
                'ordering': ['circuit', 'number', 'letter'],
                'indexes': [models.Index(fields=['circuit', 'number'], name='analytics_c_circuit_2d9ae3_idx')],
                'unique_together': {('circuit', 'number', 'letter')},
            },
        ),
        migrations.CreateModel(
            name='MarshalLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Marshal light number/ID')),
                ('letter', models.CharField(blank=True, help_text='Marshal light letter designation', max_length=10)),
                ('x', models.FloatField(help_text='X coordinate in circuit coordinate system')),
                ('y', models.FloatField(help_text='Y coordinate in circuit coordinate system')),
                ('angle', models.FloatField(help_text='Light orientation angle in degrees')),
                ('distance', models.FloatField(help_text='Distance from start line in meters')),
                ('circuit', models.ForeignKey(help_text='The circuit this marshal light belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='marshal_lights', to='analytics.circuit')),
            ],
            options={
                'verbose_name': 'Marshal Light',
                'verbose_name_plural': 'Marshal Lights',
                'ordering': ['circuit', 'number', 'letter'],
                'indexes': [models.Index(fields=['circuit', 'distance'], name='analytics_m_circuit_61f17f_idx')],
                'unique_together': {('circuit', 'number', 'letter')},
            },
        ),
        migrations.CreateModel(
            name='MarshalSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Marshal sector number/ID')),
                ('letter', models.CharField(blank=True, help_text='Marshal sector letter designation', max_length=10)),
                ('x', models.FloatField(help_text='X coordinate in circuit coordinate system')),
                ('y', models.FloatField(help_text='Y coordinate in circuit coordinate system')),
                ('angle', models.FloatField(help_text='Sector orientation angle in degrees')),
                ('distance', models.FloatField(help_text='Distance from start line in meters')),
                ('circuit', models.ForeignKey(help_text='The circuit this marshal sector belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='marshal_sectors', to='analytics.circuit')),
            ],
            options={
                'verbose_name': 'Marshal Sector',
                'verbose_name_plural': 'Marshal Sectors',
                'ordering': ['circuit', 'number', 'letter'],
                'indexes': [models.Index(fields=['circuit', 'distance'], name='analytics_m_circuit_a92086_idx')],
                'unique_together': {('circuit', 'number', 'letter')},
            },
        ),
    ]
