# Generated by Django 5.2.8 on 2025-11-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_circuit_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_temperature', models.FloatField(blank=True, help_text='Air temperature in Celsius', null=True)),
                ('track_temperature', models.FloatField(blank=True, help_text='Track surface temperature in Celsius (from FastF1 only)', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Relative humidity percentage (0-100)', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='Atmospheric pressure in millibars (mbar)', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in meters per second (m/s)', null=True)),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in degrees (0-360, where 0/360=North, 90=East, 180=South, 270=West)', null=True)),
                ('rainfall', models.BooleanField(default=False, help_text='Whether it rained during the session')),
                ('data_source', models.CharField(default='fastf1', help_text='Source of weather data (fastf1, open-meteo, manual)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(help_text='The session this weather data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='analytics.session')),
            ],
            options={
                'verbose_name': 'Session Weather',
                'verbose_name_plural': 'Session Weather',
                'ordering': ['session__race__season', 'session__race__round_number', 'session__session_number'],
                'indexes': [models.Index(fields=['rainfall'], name='analytics_s_rainfal_21e3a1_idx'), models.Index(fields=['air_temperature'], name='analytics_s_air_tem_c8038f_idx')],
            },
        ),
    ]
