# Generated by Django 5.2.8 on 2025-11-11 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_session_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLoadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_circuit', models.BooleanField(default=False, help_text='Whether circuit geometry data has been extracted')),
                ('has_weather', models.BooleanField(default=False, help_text='Whether weather data has been extracted')),
                ('has_lap_times', models.BooleanField(default=False, help_text='Whether lap time data has been extracted')),
                ('has_telemetry', models.BooleanField(default=False, help_text='Whether telemetry data has been extracted')),
                ('circuit_loaded_at', models.DateTimeField(blank=True, help_text='When circuit data was loaded', null=True)),
                ('weather_loaded_at', models.DateTimeField(blank=True, help_text='When weather data was loaded', null=True)),
                ('laps_loaded_at', models.DateTimeField(blank=True, help_text='When lap time data was loaded', null=True)),
                ('telemetry_loaded_at', models.DateTimeField(blank=True, help_text='When telemetry data was loaded', null=True)),
                ('last_api_call', models.DateTimeField(blank=True, help_text='Timestamp of last FastF1 API call for this session', null=True)),
                ('api_calls_count', models.IntegerField(default=0, help_text='Number of times session.load() was called')),
                ('prefect_metadata', models.JSONField(blank=True, default=dict, help_text='Prefect-specific metadata: flow IDs, cache keys, error history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(help_text='The session this status tracks', on_delete=django.db.models.deletion.CASCADE, related_name='load_status', to='analytics.session')),
            ],
            options={
                'verbose_name': 'Session Load Status',
                'verbose_name_plural': 'Session Load Statuses',
                'ordering': ['session__race__season', 'session__race__round_number', 'session__session_number'],
                'indexes': [models.Index(fields=['has_circuit'], name='analytics_s_has_cir_b644dd_idx'), models.Index(fields=['has_weather'], name='analytics_s_has_wea_fb426a_idx'), models.Index(fields=['has_lap_times'], name='analytics_s_has_lap_0646fc_idx'), models.Index(fields=['last_api_call'], name='analytics_s_last_ap_aee87b_idx')],
            },
        ),
    ]
