# Generated by Django 5.2.8 on 2025-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_session_loader'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRateLimitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(db_index=True, help_text='When this snapshot was taken')),
                ('requests_last_hour', models.IntegerField(help_text='Number of requests in the last hour')),
                ('requests_last_day', models.IntegerField(blank=True, help_text='Number of requests in the last 24 hours', null=True)),
                ('rate_limit_max', models.IntegerField(default=500, help_text='Maximum requests allowed per hour')),
                ('rate_limit_remaining', models.IntegerField(help_text='Remaining requests before limit')),
                ('rate_limit_status', models.CharField(choices=[('OK', 'OK - plenty of quota'), ('WARNING', 'WARNING - approaching limit'), ('EXCEEDED', 'EXCEEDED - at or over limit')], help_text='Current status', max_length=20)),
                ('ergast_requests', models.IntegerField(default=0, help_text='Requests to Ergast API')),
                ('f1_official_requests', models.IntegerField(default=0, help_text='Requests to official F1 API')),
                ('active_flows', models.JSONField(blank=True, default=list, help_text='List of active Prefect flows during this snapshot')),
            ],
            options={
                'verbose_name': 'API Rate Limit Snapshot',
                'verbose_name_plural': 'API Rate Limit Snapshots',
                'ordering': ['-snapshot_time'],
                'indexes': [models.Index(fields=['-snapshot_time'], name='analytics_a_snapsho_30dc8b_idx'), models.Index(fields=['rate_limit_status'], name='analytics_a_rate_li_9f5108_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Full URL of the API request', max_length=500)),
                ('method', models.CharField(default='GET', help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the request was made (UTC)')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Context about what triggered this request (session_id, year, round, etc.)')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code (200, 404, etc.)', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_a_timesta_a86199_idx'), models.Index(fields=['url'], name='analytics_a_url_64e3d9_idx'), models.Index(fields=['method', 'timestamp'], name='analytics_a_method_d22599_idx')],
            },
        ),
    ]
