# Generated by Django 5.2.8 on 2025-11-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_smart_imports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIRateLimitSnapshot',
        ),
        migrations.DeleteModel(
            name='APIRequestLog',
        ),
    ]
