# Generated by Django 5.2.8 on 2025-11-12 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_remove_api_rate_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField(help_text='Lap number in session (1, 2, 3, ...)')),
                ('driver_number', models.CharField(help_text="Driver's racing number", max_length=10)),
                ('lap_time', models.FloatField(blank=True, help_text='Total lap time in seconds (null if lap not completed)', null=True)),
                ('sector_1_time', models.FloatField(blank=True, help_text='Sector 1 time in seconds', null=True)),
                ('sector_2_time', models.FloatField(blank=True, help_text='Sector 2 time in seconds', null=True)),
                ('sector_3_time', models.FloatField(blank=True, help_text='Sector 3 time in seconds', null=True)),
                ('compound', models.CharField(blank=True, help_text='Tire compound (SOFT, MEDIUM, HARD, INTERMEDIATE, WET)', max_length=20)),
                ('tire_life', models.IntegerField(blank=True, help_text='Number of laps on this set of tires', null=True)),
                ('fresh_tire', models.BooleanField(default=False, help_text='Whether this lap was on fresh tires')),
                ('track_status', models.CharField(blank=True, help_text='Track status code (1=clear, 2=yellow, 4=safety car, etc.)', max_length=10)),
                ('position', models.IntegerField(blank=True, help_text='Position at end of lap', null=True)),
                ('pit_out_time', models.FloatField(blank=True, help_text='Time of pit exit in seconds since session start', null=True)),
                ('pit_in_time', models.FloatField(blank=True, help_text='Time of pit entry in seconds since session start', null=True)),
                ('speed_i1', models.FloatField(blank=True, help_text='Speed at speed trap 1 (km/h)', null=True)),
                ('speed_i2', models.FloatField(blank=True, help_text='Speed at speed trap 2 (km/h)', null=True)),
                ('speed_fl', models.FloatField(blank=True, help_text='Speed at finish line (km/h)', null=True)),
                ('speed_st', models.FloatField(blank=True, help_text='Speed trap (longest straight) in km/h', null=True)),
                ('is_personal_best', models.BooleanField(default=False, help_text="Whether this was driver's fastest lap in session")),
                ('is_accurate', models.BooleanField(default=True, help_text='Whether lap timing is accurate (from FastF1)')),
                ('lap_start_time', models.FloatField(blank=True, help_text='Lap start time in seconds since session start', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(help_text='Driver who completed this lap', on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='analytics.driver')),
                ('session', models.ForeignKey(help_text='The session this lap belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='analytics.session')),
                ('team', models.ForeignKey(blank=True, help_text='Team the driver was racing for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='analytics.team')),
            ],
            options={
                'verbose_name': 'Lap',
                'verbose_name_plural': 'Laps',
                'ordering': ['session', 'lap_number', 'driver'],
            },
        ),
        migrations.CreateModel(
            name='PitStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.IntegerField(help_text='Stop number in session for this driver (1st stop, 2nd stop, etc.)')),
                ('lap_number', models.IntegerField(help_text='Lap number when pit stop occurred')),
                ('pit_in_time', models.FloatField(blank=True, help_text='Time of pit entry (seconds since session start)', null=True)),
                ('pit_out_time', models.FloatField(blank=True, help_text='Time of pit exit (seconds since session start)', null=True)),
                ('pit_duration', models.FloatField(blank=True, help_text='Total pit stop duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(help_text='Driver who made the pit stop', on_delete=django.db.models.deletion.CASCADE, related_name='pit_stops', to='analytics.driver')),
                ('lap', models.ForeignKey(blank=True, help_text='The lap on which the pit stop occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pit_stop', to='analytics.lap')),
                ('session', models.ForeignKey(help_text='The session this pit stop occurred in', on_delete=django.db.models.deletion.CASCADE, related_name='pit_stops', to='analytics.session')),
            ],
            options={
                'verbose_name': 'Pit Stop',
                'verbose_name_plural': 'Pit Stops',
                'ordering': ['session', 'lap_number', 'driver'],
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_speed', models.FloatField(blank=True, help_text='Maximum speed during lap (km/h)', null=True)),
                ('min_speed', models.FloatField(blank=True, help_text='Minimum speed during lap (km/h)', null=True)),
                ('avg_speed', models.FloatField(blank=True, help_text='Average speed during lap (km/h)', null=True)),
                ('throttle_pct_full', models.FloatField(blank=True, help_text='Percentage of lap at full throttle (100%)', null=True)),
                ('throttle_pct_avg', models.FloatField(blank=True, help_text='Average throttle application (%)', null=True)),
                ('brake_pct', models.FloatField(blank=True, help_text='Percentage of lap spent braking', null=True)),
                ('max_gear', models.IntegerField(blank=True, help_text='Highest gear used during lap', null=True)),
                ('max_rpm', models.IntegerField(blank=True, help_text='Maximum engine RPM during lap', null=True)),
                ('avg_rpm', models.IntegerField(blank=True, help_text='Average engine RPM during lap', null=True)),
                ('drs_activations', models.IntegerField(default=0, help_text='Number of times DRS was activated during lap')),
                ('drs_distance', models.FloatField(blank=True, help_text='Total distance with DRS active (meters)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lap', models.OneToOneField(help_text='The lap this telemetry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='analytics.lap')),
            ],
            options={
                'verbose_name': 'Telemetry',
                'verbose_name_plural': 'Telemetry',
            },
        ),
        migrations.AddIndex(
            model_name='lap',
            index=models.Index(fields=['session', 'driver'], name='analytics_l_session_fb3a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='lap',
            index=models.Index(fields=['session', 'lap_number'], name='analytics_l_session_55b2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='lap',
            index=models.Index(fields=['compound'], name='analytics_l_compoun_fb2c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='lap',
            index=models.Index(fields=['lap_time'], name='analytics_l_lap_tim_6bf994_idx'),
        ),
        migrations.AddIndex(
            model_name='lap',
            index=models.Index(fields=['is_personal_best'], name='analytics_l_is_pers_ebee9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lap',
            unique_together={('session', 'driver', 'lap_number')},
        ),
        migrations.AddIndex(
            model_name='pitstop',
            index=models.Index(fields=['session', 'driver'], name='analytics_p_session_8bb9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='pitstop',
            index=models.Index(fields=['lap_number'], name='analytics_p_lap_num_4cbd57_idx'),
        ),
        migrations.AddIndex(
            model_name='pitstop',
            index=models.Index(fields=['pit_duration'], name='analytics_p_pit_dur_dd1b80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pitstop',
            unique_together={('session', 'driver', 'stop_number')},
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['max_speed'], name='analytics_t_max_spe_7e5910_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['throttle_pct_full'], name='analytics_t_throttl_fe405f_idx'),
        ),
    ]
