# Generated by Django 5.2.8 on 2025-11-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_telemetry_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='abbreviation',
            field=models.CharField(blank=True, help_text="Three-letter driver abbreviation (e.g., 'VER', 'HAM', 'RUS')", max_length=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_number',
            field=models.CharField(blank=True, help_text="Driver's racing number (e.g., '1', '44', '63')", max_length=10),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['driver_number'], name='analytics_d_driver__52eae5_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['abbreviation'], name='analytics_d_abbrevi_a8faea_idx'),
        ),
    ]
