# Generated by Django 5.2.8 on 2026-03-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0012_session_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="lap",
            name="is_fastest_lap",
            field=models.BooleanField(
                default=False,
                help_text="Whether this was the fastest lap of the entire session (across all drivers)",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="safety_car_laps",
            field=models.IntegerField(
                blank=True,
                help_text="Number of laps run under Safety Car or VSC during this session",
                null=True,
            ),
        ),
    ]
