# Generated by Django 6.0.3 on 2026-03-04 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('circuit_length', models.FloatField(blank=True, null=True)),
                ('total_corners', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=30)),
                ('sessions_processed', models.IntegerField(default=0)),
                ('sessions_skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('event_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_format', models.CharField(max_length=50)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.circuit')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
            options={
                'unique_together': {('season', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'unique_together': {('event', 'session_type')},
            },
        ),
        migrations.CreateModel(
            name='SessionCollectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('lap_count', models.IntegerField(default=0)),
                ('weather_sample_count', models.IntegerField(default=0)),
                ('result_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
            options={
                'unique_together': {('season', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('driver_number', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'unique_together': {('season', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField()),
                ('lap_time', models.DurationField(blank=True, null=True)),
                ('sector1_time', models.DurationField(blank=True, null=True)),
                ('sector2_time', models.DurationField(blank=True, null=True)),
                ('sector3_time', models.DurationField(blank=True, null=True)),
                ('pit_in_time', models.DurationField(blank=True, null=True)),
                ('pit_out_time', models.DurationField(blank=True, null=True)),
                ('is_pit_in_lap', models.BooleanField(default=False)),
                ('is_pit_out_lap', models.BooleanField(default=False)),
                ('stint', models.IntegerField(blank=True, null=True)),
                ('compound', models.CharField(blank=True, max_length=20, null=True)),
                ('tyre_life', models.IntegerField(blank=True, null=True)),
                ('track_status', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_personal_best', models.BooleanField(default=False)),
                ('is_accurate', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
            options={
                'unique_together': {('session', 'driver', 'lap_number')},
            },
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('classified_position', models.CharField(max_length=10)),
                ('grid_position', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('points', models.FloatField(default=0)),
                ('time', models.DurationField(blank=True, null=True)),
                ('fastest_lap_rank', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'unique_together': {('session', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='WeatherSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('air_temp', models.FloatField()),
                ('track_temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.IntegerField()),
                ('rainfall', models.BooleanField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
            options={
                'unique_together': {('session', 'timestamp')},
            },
        ),
    ]
